### ISSUE TITLE
The model file is damaged. Can you give me a new download address

### ISSUE THREAD

**Issue by 734321887** [naver/dope#1]

**Comment by quyanqiu** [comment]
same problem，please re-uploaded

**Comment by PhilippeWeinzaepfel** [comment]
sorry for that, it was due to a short maintenance on the server that hosts the files
the links should work again

**Comment by quyanqiu** [comment]
@PhilippeWeinzaepfel Em Actually the link is valid,but the tgz file is broken, I can not use tar zxvf DOPE_v1_0_0.pth.tgz to unzip your model file

**Comment by PhilippeWeinzaepfel** [comment]
Oh sorry, the instructions were not clear enough.
Just place the file `*.pth.tgz` in a folder named `models/`, and the `torch.load` function will take care of loading the file. You do not need to extract anyfile from the file that has been downloaded.
