### ISSUE TITLE
Could you share the 3D keypoint visualization code?

### ISSUE THREAD

**Issue by hyeokhyen** [naver/dope#3]
I would like to use your 3D model. Could you share the visualization code for the 3D model?
Just for clarification, I see that hand and face are visualized only when the person is large enough in the scene.
Which parameter shall I tune to make it available across multiple people in the scene?

**Comment by PhilippeWeinzaepfel** [comment]
Hi,

You are raising multiple points here.

* "I would like to use your 3D model"
I am not sure what 3D model refers to, the current release does not use the 3D pose predictions that we make but you can find the estimated 3D poses for bodies, hands and faces in the postprocessing output, if we do not make use of it.

* "Could you share the visualization code for the 3D model?"
We will include that in a future commit that we plan for late November / early December. 

* "Just for clarification, I see that hand and face are visualized only when the person is large enough in the scene. Which parameter shall I tune to make it available across multiple people in the scene?"
Hands and faces are visualized when they are detected. 
For hands, we are aware that some results in the wild are a bit disappointing and many hands that seem obvious to detect are missing. We are working on it and have two hypothesis for that (a) the fact that the hand expert is trained on synthetic data only (from the RenderedHand dataset) ; (b) an issue with the differnce of scales between the hand datasets and real-world images. We will release a model in the future if we get improvements on that aspect, but nothing should be expected before early next year.
For faces, we did not notice too much issues, at least without other challenge like huge motion blur, etc. For sure, if faces are too small their poses would be hard to estimate, but overall we found the results pretty satisfactory.
Feel free to send me an email with the kind of images where DOPE performs poorly, even if I do not think I can do anything for now, it might be interesting for us to know the current failure cases for future long-term improvements.
Notice also that the realtime model might give better results for small faces/hands as it was trained on smaller resolution images.
Finally, you are asking if a parameter can be tuned ; there are some detection thresholds in the ppi parameters ; but if they are detected with the default values, it is likely the detection scores will be extremely low and the estimated poses absolutely not accurate ; so I would say it won't help you to put lower values for these detection thresholds.

**Comment by PhilippeWeinzaepfel** [comment]
I have just pushed the code that take cares of 3D visualization. Enjoy.
