### ISSUE TITLE
What is the output unit?

### ISSUE THREAD

**Issue by wangzheallen** [naver/dope#5]
I output the detection in dope.py
'print(bodies['pose3d'])'

The output looks like below:
[[[ 0.1027476  -0.9983025  -0.2434892 ]
  [ 0.05194647 -1.048977    0.01026398]
  [ 0.01536132 -0.61581534 -0.20925102]
  [-0.02394905 -0.65166116  0.00149343]
  [ 0.03357595 -0.24209553 -0.1110288 ]
  [-0.04095394 -0.26142696  0.01971188]
  [ 0.24329491  0.36956102 -0.5632785 ]
  [-0.1394532   0.13668314  0.60007966]
  [ 0.17632614  0.32281047 -0.38153175]
  [-0.07703314  0.1487883   0.46362835]
  [ 0.05980128  0.26056466 -0.11758821]
  [-0.06213674  0.21221231  0.2062478 ]
  [-0.04326393  0.4115648   0.06155768]]]

with shape (1,13,3)
May I ask what is the unit in this output?
Is it in format [x_1, x_2, .... x_17, y_1, y_2, ..., y_17, z_1, z_2, ..., z_17]? 
Is it in camera coordinate?
What is the joint index name?
Do you have its performance on H36M in terms of body joint evaluation (MPJPE/PCK3D)?

Thanks

**Comment by PhilippeWeinzaepfel** [comment]
Hi,

The order of the 13 body keypoints are: 
* 0: right ankle
* 1: left ankle
* 2: right knee
* 3: left knee
* 4: right hip
* 5: left hip
* 6: right wrist
* 7: left wrist
* 8: right elbow
* 9: left elbow
* 10: right shoulder
* 11: left shoulder
* 12: head

For each joint, there is 3 coordinates corresponding to x, y, z.

The coordinates for the bodies are in meters, where the point (0,0,0) is in the body center. The axis are aligned with the camera viewpoint. The x- and y- axis of the bodies follow the pixel coordinate axis, which might not be standard in some datasets, in which case you might need to inverse them as in L56-57 of the file visu3d.py . The z-axis is orthogonal to the image plane.

We did not evaluate the model on Human3.6M as we aim to tackle the cases of in-the-wild images and we did not use the same set/definition of the keypoints.

**Comment by wangzheallen** [comment]
Thanks for your kind answer!
