### ISSUE TITLE
Empty model download link

### ISSUE THREAD

**Issue by llxxll12345** [naver/dope#6]
Hello, I tried to download the model from the link provided. I tried both links but none of them worked. I'm accessing from Georgia, United States.

**Comment by PhilippeWeinzaepfel** [comment]
Hi,

I don't have any issue currently (not sure if there were any earlier).
Can you try again and let me know if you still encounter the issue.
If yes, could you try while doing wget directly the link such as http://download.europe.naverlabs.com/ComputerVision/DOPE_models/DOPE_v1_0_0.pth.tgz or trying to open that directly in the browser ?

Best regards

**Comment by llxxll12345** [comment]
Hello, It is related to some issues with my browser. I used wget and now it works. Thank you!
